"""Shell completion script generation for gensay.

``gensay completions bash|zsh|fish`` prints a completion script to stdout.
The scripts are generated by introspecting the real argparse parsers in
:mod:`gensay.main`, so flags, subcommands, provider names, formats, and
config keys can never drift from the actual CLI.

Voice names are the one dynamic piece: the generated scripts call the
hidden ``gensay --print-voice-names [-p PROVIDER]`` helper at Tab time.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass

SHELLS = ("bash", "zsh", "fish")

# Completion behavior per option, keyed by argparse dest
_FILE_DESTS = {"file", "output", "socket"}
_DIR_DESTS = {"runtime_dir"}
_VOICE_DESTS = {"voice"}


@dataclass(frozen=True)
class Opt:
    """One CLI option, as the shells need to know it."""

    strings: tuple[str, ...]
    help: str
    kind: str  # "flag" | "choices" | "voice" | "file" | "dir" | "value"
    choices: tuple[str, ...] = ()


@dataclass(frozen=True)
class SubCmd:
    """A subcommand (of `gensay daemon` / `gensay config`)."""

    name: str
    help: str
    opts: tuple[Opt, ...]
    key_positional: bool = False  # first positional completes config keys


@dataclass
class CliSpec:
    """Everything the shell script templates need."""

    main_opts: tuple[Opt, ...]
    daemon_cmds: tuple[SubCmd, ...]
    config_cmds: tuple[SubCmd, ...]
    config_keys: tuple[str, ...]


def _clean_help(action: argparse.Action) -> str:
    """First line of help, with argparse %-interpolation resolved."""
    text = action.help or ""
    if "%(default)s" in text:
        text = text.replace("%(default)s", str(action.default))
    text = " ".join(text.split())
    # Keep descriptions short for completion listings
    for stop in (". ", " ("):
        if stop in text:
            text = text.split(stop, 1)[0]
    return text.strip().rstrip(".")


def _opt_kind(action: argparse.Action) -> tuple[str, tuple[str, ...]]:
    if action.nargs == 0:
        return "flag", ()
    if action.dest in _VOICE_DESTS:
        return "voice", ()
    if action.choices:
        return "choices", tuple(str(c) for c in action.choices)
    if action.dest in _FILE_DESTS:
        return "file", ()
    if action.dest in _DIR_DESTS:
        return "dir", ()
    return "value", ()


def _parser_opts(parser: argparse.ArgumentParser) -> tuple[Opt, ...]:
    out: list[Opt] = []
    for action in parser._actions:  # noqa: SLF001 - stable argparse internals
        if not action.option_strings or action.help is argparse.SUPPRESS:
            continue
        kind, choices = _opt_kind(action)
        out.append(
            Opt(
                strings=tuple(action.option_strings),
                help=_clean_help(action),
                kind=kind,
                choices=choices,
            )
        )
    return tuple(out)


def _subcommands(parser: argparse.ArgumentParser) -> tuple[SubCmd, ...]:
    out: list[SubCmd] = []
    for action in parser._actions:  # noqa: SLF001
        if not isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            continue
        helps = {ca.dest: (ca.help or "") for ca in action._choices_actions}  # noqa: SLF001
        for name, sub in action.choices.items():
            key_positional = any(
                not a.option_strings and a.dest == "key"
                for a in sub._actions  # noqa: SLF001
            )
            out.append(
                SubCmd(
                    name=name,
                    help=" ".join(helps.get(name, "").split()),
                    opts=_parser_opts(sub),
                    key_positional=key_positional,
                )
            )
    return tuple(out)


def build_spec() -> CliSpec:
    """Introspect the real gensay parsers into a CliSpec."""
    from .main import create_config_parser, create_daemon_parser, create_parser
    from .user_config import KNOWN_KEYS

    return CliSpec(
        main_opts=_parser_opts(create_parser()),
        daemon_cmds=_subcommands(create_daemon_parser()),
        config_cmds=_subcommands(create_config_parser()),
        config_keys=tuple(KNOWN_KEYS),
    )


def _all_flags(opts: tuple[Opt, ...]) -> list[str]:
    return [s for o in opts for s in o.strings]


# ---------------------------------------------------------------------------
# bash
# ---------------------------------------------------------------------------


def _bash_value_case(opts: tuple[Opt, ...], indent: str) -> str:
    """A bash `case "$prev" in ...` body completing option values."""
    lines: list[str] = []
    for o in opts:
        if o.kind == "flag":
            continue
        pattern = "|".join(o.strings)
        if o.kind == "choices":
            body = f'COMPREPLY=( $(compgen -W "{" ".join(o.choices)}" -- "$cur") )'
        elif o.kind == "voice":
            body = 'local IFS=$\'\\n\'; COMPREPLY=( $(compgen -W "$(__gensay_voices)" -- "$cur") )'
        elif o.kind == "file":
            body = 'COMPREPLY=( $(compgen -f -- "$cur") )'
        elif o.kind == "dir":
            body = 'COMPREPLY=( $(compgen -d -- "$cur") )'
        else:  # value: option takes an arg we can't complete
            body = "COMPREPLY=()"
        lines.append(f"{indent}{pattern}) {body}; return;;")
    return "\n".join(lines)


def render_bash(spec: CliSpec) -> str:
    main_flags = " ".join(_all_flags(spec.main_opts))
    daemon_names = " ".join(c.name for c in spec.daemon_cmds)
    config_names = " ".join(c.name for c in spec.config_cmds)
    config_keys = " ".join(spec.config_keys)

    daemon_flag_cases = "\n".join(
        f"                {c.name}) COMPREPLY=( $(compgen -W "
        f'"{" ".join(_all_flags(c.opts))}" -- "$cur") );;'
        for c in spec.daemon_cmds
    )
    daemon_value_cases = _bash_value_case(
        tuple({o.strings: o for c in spec.daemon_cmds for o in c.opts}.values()),
        indent="                ",
    )
    config_flag_cases = "\n".join(
        f"                {c.name}) COMPREPLY=( $(compgen -W "
        f'"{" ".join(_all_flags(c.opts))}" -- "$cur") );;'
        for c in spec.config_cmds
    )
    config_key_cmds = "|".join(c.name for c in spec.config_cmds if c.key_positional)
    main_value_cases = _bash_value_case(spec.main_opts, indent="        ")

    return f"""\
# bash completion for gensay
# Install: gensay completions bash > ~/.local/share/bash-completion/completions/gensay
# (or source this file from ~/.bashrc)

__gensay_voices() {{
    local p="" i
    for ((i=1; i < COMP_CWORD; i++)); do
        case "${{COMP_WORDS[i]}}" in
            -p|--provider) p="${{COMP_WORDS[i+1]:-}}";;
        esac
    done
    if [ -n "$p" ]; then
        command gensay --print-voice-names -p "$p" 2>/dev/null
    else
        command gensay --print-voice-names 2>/dev/null
    fi
}}

_gensay() {{
    local cur prev
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    case "${{COMP_WORDS[1]:-}}" in
        daemon)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "{daemon_names}" -- "$cur") )
                return
            fi
            case "$prev" in
{daemon_value_cases}
            esac
            case "${{COMP_WORDS[2]:-}}" in
{daemon_flag_cases}
            esac
            return
            ;;
        config)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "{config_names}" -- "$cur") )
                return
            fi
            if [ "$COMP_CWORD" -eq 3 ]; then
                case "${{COMP_WORDS[2]}}" in
                    {config_key_cmds})
                        COMPREPLY=( $(compgen -W "{config_keys}" -- "$cur") )
                        return
                        ;;
                esac
            fi
            case "${{COMP_WORDS[2]:-}}" in
{config_flag_cases}
            esac
            return
            ;;
        completions)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "{" ".join(SHELLS)}" -- "$cur") )
            fi
            return
            ;;
    esac

    case "$prev" in
{main_value_cases}
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "{main_flags}" -- "$cur") )
    elif [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "daemon config completions {main_flags}" -- "$cur") )
    fi
}}

complete -F _gensay gensay
"""


# ---------------------------------------------------------------------------
# zsh
# ---------------------------------------------------------------------------


def _zsh_escape_help(text: str) -> str:
    return text.replace("'", "'\\''").replace("[", "(").replace("]", ")").replace(":", " -")


def _zsh_value_spec(o: Opt) -> str:
    if o.kind == "choices":
        return f":value:({' '.join(o.choices)})"
    if o.kind == "voice":
        return ":voice:__gensay_voices"
    if o.kind == "file":
        return ":file:_files"
    if o.kind == "dir":
        return ":directory:_files -/"
    if o.kind == "value":
        return ":value: "
    return ""


def _zsh_arg_specs(opts: tuple[Opt, ...]) -> list[str]:
    specs: list[str] = []
    for o in opts:
        h = _zsh_escape_help(o.help)
        value = _zsh_value_spec(o)
        if len(o.strings) == 1:
            specs.append(f"'{o.strings[0]}[{h}]{value}'")
        else:
            group = " ".join(o.strings)
            alts = ",".join(o.strings)
            specs.append(f"'({group})'{{{alts}}}'[{h}]{value}'")
    return specs


def render_zsh(spec: CliSpec) -> str:
    def arg_lines(opts: tuple[Opt, ...], extra: tuple[str, ...] = ()) -> str:
        specs = _zsh_arg_specs(opts) + list(extra)
        return " \\\n        ".join(specs)

    daemon_descs = " ".join(f"'{c.name}:{_zsh_escape_help(c.help)}'" for c in spec.daemon_cmds)
    config_descs = " ".join(f"'{c.name}:{_zsh_escape_help(c.help)}'" for c in spec.config_cmds)
    key_spec = f"'1:key:({' '.join(spec.config_keys)})'"

    daemon_cases = "\n".join(
        f"""        {c.name})
            _arguments -S \\
        {arg_lines(c.opts)}
            ;;"""
        for c in spec.daemon_cmds
    )
    config_cases = "\n".join(
        f"""        {c.name})
            _arguments -S \\
        {arg_lines(c.opts, (key_spec,) if c.key_positional else ())}
            ;;"""
        for c in spec.config_cmds
    )

    return f"""\
#compdef gensay
# zsh completion for gensay
# Install: gensay completions zsh > "${{fpath[1]}}/_gensay"
# (any directory on $fpath works, e.g. mkdir -p ~/.zfunc; add it to fpath)

__gensay_voices() {{
    local p="" i
    for ((i = 2; i <= $#words; i++)); do
        case "${{words[i]}}" in
            -p|--provider) p="${{words[i+1]:-}}";;
        esac
    done
    local -a voices
    if [[ -n "$p" ]]; then
        voices=(${{(f)"$(command gensay --print-voice-names -p "$p" 2>/dev/null)"}})
    else
        voices=(${{(f)"$(command gensay --print-voice-names 2>/dev/null)"}})
    fi
    (( $#voices )) && _describe -t voices 'voice' voices
}}

_gensay() {{
    local curcontext="$curcontext" state line

    if (( CURRENT == 2 )); then
        local -a subcmds
        subcmds=(
            'daemon:Manage the warm TTS inference daemon'
            'config:Manage per-user gensay defaults'
            'completions:Print shell completion script (bash, zsh, fish)'
        )
        _describe -t commands 'gensay command' subcmds
    fi

    case "${{words[2]}}" in
        daemon)
            if (( CURRENT == 3 )); then
                local -a dcmds
                dcmds=({daemon_descs})
                _describe -t commands 'daemon command' dcmds
                return
            fi
            words=("${{(@)words[3,-1]}}")
            (( CURRENT -= 2 ))
            case "${{words[1]}}" in
{daemon_cases}
            esac
            return
            ;;
        config)
            if (( CURRENT == 3 )); then
                local -a ccmds
                ccmds=({config_descs})
                _describe -t commands 'config command' ccmds
                return
            fi
            words=("${{(@)words[3,-1]}}")
            (( CURRENT -= 2 ))
            case "${{words[1]}}" in
{config_cases}
            esac
            return
            ;;
        completions)
            (( CURRENT == 3 )) && _values 'shell' {" ".join(SHELLS)}
            return
            ;;
    esac

    _arguments -S \\
        {arg_lines(spec.main_opts, ("'*:message: '",))}
}}

_gensay "$@"
"""


# ---------------------------------------------------------------------------
# fish
# ---------------------------------------------------------------------------


def _fish_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "\\'")


def _fish_opt_flags(o: Opt) -> str:
    parts: list[str] = []
    for s in o.strings:
        if s.startswith("--"):
            parts.append(f"-l {s[2:]}")
        elif len(s) == 2:
            parts.append(f"-s {s[1]}")
        else:  # e.g. --no-via-daemon handled above; odd shorts: -o form
            parts.append(f"-o {s.lstrip('-')}")
    return " ".join(parts)


def _fish_complete_lines(cond: str, opts: tuple[Opt, ...]) -> list[str]:
    lines: list[str] = []
    for o in opts:
        flags = _fish_opt_flags(o)
        desc = f" -d '{_fish_escape(o.help)}'" if o.help else ""
        if o.kind == "flag":
            lines.append(f"complete -c gensay -n {cond} {flags}{desc}")
        elif o.kind == "choices":
            lines.append(
                f"complete -c gensay -n {cond} {flags} -x -a '{' '.join(o.choices)}'{desc}"
            )
        elif o.kind == "voice":
            lines.append(f"complete -c gensay -n {cond} {flags} -x -a '(__gensay_voices)'{desc}")
        elif o.kind in ("file", "dir"):
            lines.append(f"complete -c gensay -n {cond} {flags} -rF{desc}")
        else:  # value
            lines.append(f"complete -c gensay -n {cond} {flags} -x{desc}")
    return lines


def render_fish(spec: CliSpec) -> str:
    lines: list[str] = [
        "# fish completion for gensay",
        "# Install: gensay completions fish > ~/.config/fish/completions/gensay.fish",
        "",
        "function __gensay_voices",
        "    set -l p ''",
        "    set -l tokens (commandline -opc)",
        "    for i in (seq (count $tokens))",
        "        if contains -- $tokens[$i] -p --provider",
        "            and test (count $tokens) -gt $i",
        "            set p $tokens[(math $i + 1)]",
        "        end",
        "    end",
        '    if test -n "$p"',
        "        command gensay --print-voice-names -p $p 2>/dev/null",
        "    else",
        "        command gensay --print-voice-names 2>/dev/null",
        "    end",
        "end",
        "",
        "# Disable default file completion; options that take files re-enable it",
        "complete -c gensay -f",
        "",
    ]

    main_cond = '"not __fish_seen_subcommand_from daemon config completions"'
    lines.append("# Subcommands")
    for name, desc in (
        ("daemon", "Manage the warm TTS inference daemon"),
        ("config", "Manage per-user gensay defaults"),
        ("completions", "Print shell completion script"),
    ):
        lines.append(f"complete -c gensay -n '__fish_use_subcommand' -a {name} -d '{desc}'")
    lines.append("")

    lines.append("# Main command options")
    lines.extend(_fish_complete_lines(main_cond, spec.main_opts))
    lines.append("")

    lines.append("# gensay completions <shell>")
    lines.append(
        "complete -c gensay -n '__fish_seen_subcommand_from completions' "
        f"-x -a '{' '.join(SHELLS)}'"
    )
    lines.append("")

    for group, cmds in (("daemon", spec.daemon_cmds), ("config", spec.config_cmds)):
        names = " ".join(c.name for c in cmds)
        lines.append(f"# gensay {group} subcommands")
        for c in cmds:
            cond = (
                f'"__fish_seen_subcommand_from {group}; '
                f'and not __fish_seen_subcommand_from {names}"'
            )
            desc = f" -d '{_fish_escape(c.help)}'" if c.help else ""
            lines.append(f"complete -c gensay -n {cond} -x -a {c.name}{desc}")
        for c in cmds:
            cond = (
                f'"__fish_seen_subcommand_from {group}; and __fish_seen_subcommand_from {c.name}"'
            )
            if c.key_positional:
                lines.append(f"complete -c gensay -n {cond} -x -a '{' '.join(spec.config_keys)}'")
            lines.extend(_fish_complete_lines(cond, c.opts))
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------

_RENDERERS = {"bash": render_bash, "zsh": render_zsh, "fish": render_fish}


def render(shell: str) -> str:
    """Render the completion script for one shell."""
    return _RENDERERS[shell](build_spec())


def completions_main(argv: list[str] | None = None) -> None:
    """Entry for `gensay completions ...`."""
    parser = argparse.ArgumentParser(
        prog="gensay completions",
        description="Print a shell completion script to stdout",
        epilog=(
            "Install:\n"
            "  bash: gensay completions bash > "
            "~/.local/share/bash-completion/completions/gensay\n"
            '  zsh:  gensay completions zsh > "${fpath[1]}/_gensay"\n'
            "  fish: gensay completions fish > "
            "~/.config/fish/completions/gensay.fish"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("shell", choices=SHELLS, help="Target shell")
    args = parser.parse_args(argv)
    sys.stdout.write(render(args.shell))
